name: Deployment stage

on:
  workflow_call:
    inputs:
      environments:
        description: List of environments to deploy to (String array)
        required: true
        type: string
      commit_sha:
        description: Commit SHA used to fetch ADO pipeline and docker image
        required: true
        type: string
      pr_number:
        description: Pull request number when used in a pull request
        required: false
        type: string

    secrets:
      client_id:
        description: 'The Azure Client ID.'
        required: true
      tenant_id:
        description: 'The Azure Tenant ID.'
        required: true
      subscription_id:
        description: 'The Azure Subscription ID.'
        required: true

  workflow_dispatch:
    inputs:
      environments:
        description: List of environments to deploy to (String array)
        required: true
        type: string
      commit_sha:
        description: Commit SHA used to fetch ADO pipeline and docker image
        required: true
        type: string
      pr_number:
        description: Pull request number when used in a pull request
        required: false
        type: string

    secrets:
      client_id:
        description: 'The Azure Client ID.'
        required: true
      tenant_id:
        description: 'The Azure Tenant ID.'
        required: true
      subscription_id:
        description: 'The Azure Subscription ID.'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
      max-parallel: 1
    environment: ${{ matrix.environment }}
    concurrency: deploy-${{ matrix.environment }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          client-id: ${{ secrets.client_id }}
          tenant-id: ${{ secrets.tenant_id }}
          subscription-id: ${{ secrets.subscription_id }}

      - name: Make script executable
        run: chmod +x scripts/bash/wait_ado_pipeline.sh

      - name: Call deployment pipeline
        shell: bash
        env:
          COMMIT_SHA: ${{ inputs.commit_sha }}
          ENVIRONMENT_NAME: ${{ matrix.environment }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          # Define common variables
          organisation='https://dev.azure.com/nhse-dtos'
          project_name='dtos-cohort-manager'

          # Define which tests to run based on the environment
          declare -A test_types=(
            ["development"]="smoke_e2e"
          )

          # Derive the short SHA from the provided commit
          git_short_sha=$(git rev-parse --short "$COMMIT_SHA")

          # Get the PR Info

          PR_INFO=$(gh api repos/${{ github.repository }}/commits/${COMMIT_SHA}/pulls --jq '.[0] | {number: .number, branch: .head.ref}')

          PR_NUM=$(echo "$PR_INFO" | jq -r '.number')
          DEVTEST_PR_NUM_TAG="devtest_pr${PR_NUM}"

          BRANCH_NAME=$(echo "$PR_INFO" | jq -r '.branch')

          echo "Name of the branch to use in ADO: ${BRANCH_NAME}"
          echo "Name of the image to be used for Function Apps configuration: ${DEVTEST_PR_NUM_TAG}"

          # Prepare parameters as separate key=value tokens
          param_image="dockerImageTag=${DEVTEST_PR_NUM_TAG}"
          param_tests="testTypes=[${test_types[$ENVIRONMENT_NAME]}]"

          # echo "Starting Azure devops pipeline \"Deploy to Azure - Core ${ENVIRONMENT_NAME}\"..."
          # RUN_ID=$(az pipelines run \
          #   --branch "${BRANCH_NAME}" \
          #   --commit-id "$COMMIT_SHA" \
          #   --name "Deploy to Azure - Core ${ENVIRONMENT_NAME}" \
          #   --org "${organisation}" \
          #   --project "${project_name}" \
          #   --parameters "$param_image" "$param_tests" \
          #   --output tsv --query id)

          # echo "Click here to view the ADO pipeline: ${organisation}/${project_name}/_build/results?buildId=${RUN_ID}"

          # scripts/bash/wait_ado_pipeline.sh "$RUN_ID" "${organisation}" "${project_name}" 1800
